# Generated by Django 2.1.1 on 2018-10-02 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181002_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readnum',
            old_name='read_num',
            new_name='readed_num',
        ),
    ]
