# Generated by Django 2.1.1 on 2018-10-02 06:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_readnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='readnum',
            name='blog',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Blog'),
            preserve_default=False,
        ),
    ]
