# Generated by Django 2.1.1 on 2018-10-02 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181002_1454'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReadNum',
            new_name='ReadedNum',
        ),
    ]
